export const SET_NEXT_STATE = 'SET_NEXT_STATE';
export const SET_GREENHOUSE_GASES_VALUES = 'SET_GREENHOUSE_GASES_VALUES';
export const SET_ALBEDO = 'SET_ALBEDO';
export const SET_FEEDBACK_VALUES = 'SET_FEEDBACK_VALUES';
export const SET_RADIATION_MODE = 'SET_RADIATION_MODE';
export const SET_IS_PAUSED = 'SET_IS_PAUSED';
