export const SET_ALBEDO_VALUES = 'SET_ALBEDO_VALUES';
export const SET_FEEDBACK_VALUES = 'SET_FEEDBACK_VALUES';
export const SET_RADIATION_MODE = 'SET_RADIATION_MODE';
export const SET_IS_PAUSED = 'SET_IS_PAUSED';
export const SET_SCALE_UNIT = 'SET_SCALE_UNIT';
export const SET_SIMULATION_MODE = 'SET_SIMULATION_MODE';
export const RESET = 'RESET';
export const INCREMENT_INTERVAL_COUNT = 'INCREMENT_INTERVAL_COUNT';
export const SET_C_TERM = 'SET_C_TERM';
export const TOGGLE_FLUXES_FILLS = 'TOGGLE_FLUXES_FILLS';
export const RESET_FLUXES_FILL = 'RESET_FLUXES_FILLS';
export const SET_SLIDER_ICE_COVER = 'SET_SLIDER_ICE_COVER';
export const SET_SLIDER_CLOUD_COVER = 'SET_SLIDER_CLOUD_COVER';
export const SET_SLIDER_CARBON_DIOXIDE = 'SET_SLIDER_CARBON_DIOXIDE';
export const SET_SLIDER_METHANE = 'SET_SLIDER_METHANE';
export const SET_THERMOMETER_VALUES = 'SET_THERMOMETER_VALUES';
export const SET_THERMOMETER_ICE_COVER = 'SET_THERMOMETER_ICE_COVER';
export const SET_VALUES_TEMPORARILY_VIA_C_TERM =
  'SET_VALUES_TEMPORARILY_VIA_C_TERM';
export const SET_VALUES_TEMPORARILY_VIA_ICE_COVER =
  'SET_VALUES_TEMPORARILY_VIA_ICE_COVER';
