export const SET_GREENHOUSE_GASES_VALUES = 'SET_GREENHOUSE_GASES_VALUES';
export const SET_ALBEDO_VALUES = 'SET_ALBEDO_VALUES';
export const SET_FEEDBACK_VALUES = 'SET_FEEDBACK_VALUES';
export const SET_RADIATION_MODE = 'SET_RADIATION_MODE';
export const SET_IS_PAUSED = 'SET_IS_PAUSED';
export const SET_SCALE_UNIT = 'SET_SCALE_UNIT';
export const SET_SIMULATION_MODE = 'SET_SIMULATION_MODE';
export const RESET = 'RESET';
